name: Update RSS

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run parser
        run: python rss.py

      - name: Commit changes
        run: |
          git config --global user.name "rss-bot"
          git config --global user.email "rss@bot.com"
          git add news.json
          git commit -m "update rss" || echo "no changes"
          git push